version: '3.5'
services:
  fp-stix-taxii:
    image: docker.frcpnt.com/fp-dim/fp-stix-taxii:latest
    environment:
      INTERNAL_TOKEN: 
      HOST_DOMAIN: localhost
      CONTROLLER_SVC_NAME: dim-controller
      CONTROLLER_PORT: 8080
      MODULE_SVC_NAME: fp-stix-taxii
      LOCAL_PORT: 8080
    restart: on-failure
    volumes:
    - ${PWD}/config:/config
    networks:
      - dim_module-net

networks:
  dim_module-net:
    external: true
